project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer:  <span class="footer-text">Made with Quarto. &copy; 2025</span>
  navbar:
    title: Aleksandar Vujic
    left:
      - text: Home
        href: index.qmd
        icon: house
      - text: CV
        href: CV.qmd
        icon: person
      - text: My Publications
        href: projects/
        icon: book
      - text: Conferences
        href: conf/
        icon: easel2
      
        
      
format:
  html:
    fontsize: 18px
    theme: [trestles, styles.scss]
  

