---
title: Professional Summary
---

<a href="files/Aleksandar_Vujic_CV_2025.pdf" download class="btn btn-primary">
  Download PDF
</a>

Responsible and reliable psychologist and researcher, highly motivated to gather knowledge and assimilate new concepts in teaching, customer support, HR, statistics, data science, analytics as well as in communications. Ready to contribute to the collective progress and the well-being of its members.

## Skills

 + R
 + Python
 + SPSS
 + Psychometrics

## Education

Eotvos Lorand University \| Budapest, Hungary \| <span class="year-text">2020 - 2025</span><br>
**PhD** 

University of Novi Sad \| Novi Sad, Serbia \| <span class="year-text">2016 - 2017</span><br>
__Master of psychology__

University of Novi Sad \| Novi Sad, Serbia \| <span class="year-text">2012 - 2016</span><br>
__Bachelor of psychology__


## Experience

Karoli Gaspar University, Budapest \| Statistics lecturer \|  <span class="year-text">Present</span>

Productive Playhouse Inc \| Transcriber \|  <span class="year-text">Jun-Nov 2024</span>

ELTE Eotvos Lorand University, Budapest \| Statistics lecturer \|  <span class="year-text">Sep-2023 – Jan-2024</span>         

### Internships

Military Medical Center, Novi Sad \| psychology intern

Preschool Institution in Novi Sad  \| psychology intern

Geriatric Center Novi Sad  \| psychology intern

## Languages

 + Serbian
 + English
 + Russian
 + Chinese
 
## Certificates

  + TOEFL
  + HSK5 / HSKK intermediate
  + <a href="https://drive.google.com/drive/folders/1FMjQB6Z8losLlthZPiBZ46VBWARX0ipt?usp=sharing" class="certlink">Nine completed tracks on <b>Data Camp</b>, 115 courses in total</a>
  + Udemy - Complete Machine learning with R