---
title: "Publications"
bibliography: Moje.bib
csl: apa.csl
output: html
---


Árok, P., Morvay-Sey, K., Vujić, A., & Szabo, A. (2024). Psychometric Properties of the Hungarian Passion Scale-8 (PS-8-HU) in Physically Active and Inactive Adults. Perceptual and Motor Skills, 00315125241296611. https://doi.org/10.1177/00315125241296611

Dinić, B. M., Raine, A., Vujić, A., & Van Dongen, J. D. M. (2022). Cross–cultural Validity of the Reactive–Proactive Aggression Questionnaire Among Adults Across Five Countries. Journal of Interpersonal Violence, 37(9–10), NP6261–NP6283. https://doi.org/10.1177/0886260520966672

Dinić, B. M., & Vujić, A. (2019). Five-Factor Model Best Describes Narcissistic Personality Inventory Across Different Item Response Formats. Psychological Reports, 122(5), 1946–1966. https://doi.org/10.1177/0033294118794404

Dinić, B. M., & Vujić, A. (2020). The Pathological Narcissism Inventory: Measurement Invariance Across Serbian and USA Samples and Further Validation. European Journal of Psychological Assessment, 36(4), 670–680. https://doi.org/10.1027/1015-5759/a000537

Köteles, F., Vujić, A., & Szabo, A. (2024). Psychometric evaluation and validation of the Hungarian version of the Physical Activity Affect Scale (PAAS-H). Mentálhigiéné És Pszichoszomatika, 25(3), 217–227. https://doi.org/10.1556/0406.2024.00059
Szabo, A., Árok, P., Vujić, A., Morvay-Sey, K., & Granziol, U. (2024). Exercise Addiction Inventory-3 (EAI-3): Psychometric properties of the Hungarian version. Mentálhigiéné És Pszichoszomatika, 25(3), 203–216. https://doi.org/10.1556/0406.2024.00064

Toth, E. E., Vujić, A., Ihász, F., Ruíz-Barquín, R., & Szabo, A. (2024). A Fullerton Functional Fitness Test-based exercise intervention for older adults yields quick physical and psychological benefits. Complementary Therapies in Clinical Practice, 57, 101880. https://doi.org/10.1016/j.ctcp.2024.101880

Tóth, E. E., Vujić, A., Ihász, F., Ruíz-Barquín, R., & Szabo, A. (2024). Psychological Resilience and Complex Movement Coordination Predict the Risk of Falls in Older Adults. Journal of Population Ageing. https://doi.org/10.1007/s12062-024-09471-8
Tóth, E. E., Vujić, A., Ihász, F., Ruíz-Barquín, R., & Szabo, A. (2025). Functional fitness and psychological well-being in older adults. BMC Geriatrics, 25(1), 9. https://doi.org/10.1186/s12877-024-05654-2

Volarov, M., Vujić, A., Adamović Zdravković, S., Kuruzović, N., Bőthe, B., & Szabo, A. (2025). Psychometric Validation of the Modified, Short Version of the Problematic Pornography Consumption Scale in Serbian. Sexual Health & Compulsivity, 1–24. https://doi.org/10.1080/26929953.2024.2448110

Vujić, A., Dinić, B. M., & Jokić-begić, N. (2022). Cyberchondria and Questionable Health Practices: The Mediation Role of Conspiracy Mentality. Studia Psychologica, 64(1), 104–117. https://doi.org/10.31577/sp.2022.01.842

Vujić, A., & Szabo, A. (2021). The connection between risk of smartphone addiction, type of smartphone use, life satisfaction, and perceived stress dataset. Data in Brief, 39, 107651. https://doi.org/10.1016/j.dib.2021.107651

Vujić, A., & Szabo, A. (2022). Hedonic use, stress, and life satisfaction as predictors of smartphone addiction. Addictive Behaviors Reports, 15, 100411. https://doi.org/10.1016/j.abrep.2022.100411

Vujić, A., Volarov, M., Latas, M., Demetrovics, Z., Kiraly, O., & Szabo, A. (2023). Are Cyberchondria and Intolerance of Uncertainty Related to Smartphone Addiction? International Journal of Mental Health and Addiction. https://doi.org/10.1007/s11469-023-01054-6

Vujić, A., Volarov, M., Latas, M., Griffiths, M. D., & Szabo, A. (2023). Psychometric Properties of the Serbian Smartphone Application-Based Addiction Scale (SABAS) and Validation of the English Version Among Non-native English Speakers. International Journal of Mental Health and Addiction. https://doi.org/10.1007/s11469-023-01013-1